name: Falcon Look App CI
on: pull_request

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker build and run
      run: |
        docker build . -t scottyfullstack/falcon-look-app
        docker run -dit -p 8000:8000 scottyfullstack/falcon-look-app
    
    - name: Run tests and coverage report
      run: coverage run -m pytest tests/ && coverage report > coverage-report

    - name: Test Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-report
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:latest
    
    - name: Create an Issue on failure
      if: ${{ failure() }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \ 
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["$GITHUB_ACTOR"],"milestone":1,"labels":["bug"]}'